// <auto-generated />
namespace Real_Estate_Application.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class UploadImageFix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UploadImageFix));
        
        string IMigrationMetadata.Id
        {
            get { return "201910142310202_UploadImageFix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
